#!/usr/bin/env bash


set -e
unset PYTHONPATH


# SET DEFAULT ARGUMENTS
SCRIPTDIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
PIPELINEDIR=$(dirname "${SCRIPTDIR}")
source "${PIPELINEDIR}"/CONFIG


# PARSE COMMAND LINE ARGUMENTS
while [[ $# -gt 0 ]]
do
  case "${1}" in
    -h|--help)
      echo "____________"
      echo "TrimMapCount"
      echo "‾‾‾‾‾‾‾‾‾‾‾‾"
      echo "Trim, map, and count FASTQ reads with icSHAPE (https://github.com/qczhang/icSHAPE), "
      echo "STAR (https://github.com/alexdobin/STAR), and HTSeq (https://github.com/htseq/htseq)."
      echo ""
      echo "For help using the TrimMapCount pipeline, visit "
      echo "https://fazallabbcm.github.io/FazalLabPipelines/."
      echo ""
      echo "____________________________________________________________________________________________"
      echo "Usage:"
      echo "  TrimMapCount --option <argument>"
      echo ""
      echo "Options:"
      echo "  -h, --help                show this help message"
      echo ""
      echo "  -r, --rawdata-dir DIR     path to directory where raw fastq files are stored"
      echo ""
      echo "  -d, --data-dir DIR        path to directory for processed data files"
      echo "                            (default is same as raw data)"
      echo ""
      echo "  -a, --adapter FILE        if the default TruSeq adapter isn't the correct adapter for your"
      echo "                            data (TrimMapCount/scripts/icSHAPE/data/adapter/adapter.fa), you"
      echo "                            can supply the path to another adapter FASTA file for trimming"
      echo ""
      echo "  -i, --interactive         run the pipeline interactively instead of submitting a batch job"
      echo "                            (make sure to switch to an interactive node)"
      echo "‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾"
      exit 0
      ;;
    -r|--rawdata-dir)
      RAWDATADIR="${2}"
      shift
      shift
      ;;
    -d|--data-dir)
      DATADIR="${2}"
      shift
      shift
      ;;
    -a|--adapter)
      ADAPTER_FILE="${2}"
      shift
      shift
      ;;
    -i|--interactive)
      INTERACTIVE=TRUE
      shift
      ;;
    -g|--genome-dir)
      GENOMEDIR="${2}"
      shift
      shift
      ;;
    -e|--env-dir)
      ENVDIR="${2}"
      shift
      shift
      ;;
    -t|--temp-dir)
      TEMPDIR="${2}"
      shift
      shift
      ;;
    -*|--*)
      echo "Unknown option: ${1}"
      exit 1
      ;;
    *)
      echo "Unknown argument: ${1}"
      exit 1
      ;;
  esac
done


# HANDLE UNSPECIFIED ARGUMENTS
if [[ -z "${RAWDATADIR}" ]]
then
  echo "  Raw data directory not specified. Please supply path to raw data directory."
  exit 1
fi
if [[ -z "${DATADIR}" ]]
then
  DATADIR="${RAWDATADIR}"
fi
if [[ -z "${ADAPTER_FILE}" ]]
then
  ADAPTER_FILE="${SCRIPTDIR}"/icSHAPE/data/adapter/adapter.fa
fi



# PREPARE ENVIRONMENT
# Activate environment
export PATH="${ENVDIR}"/bin:"${PATH}"
# Avoid dumping too much temporary data into system tmp directory
export TMPDIR="${TEMPDIR}"
export TEMP="${TEMPDIR}"
export TMP="${TEMPDIR}"


# PRINT SETTINGS FOR USER
echo ""
echo "  Raw data directory:        ${RAWDATADIR}"
echo "  Processed data directory:  ${DATADIR}"
#echo "  Adapter file:              ${ADAPTER_FILE}"
#echo "  Genome directory:          ${GENOMEDIR}"
#echo "  Environment directory:     ${ENVDIR}"
#echo "  Temporary directory:       ${TEMPDIR}"
echo ""
echo "  Log file will be created in your current directory:  ${PWD}"
echo ""


# START PIPELINE
while true
do
  read -p "Do you wish to start the TrimMapCount pipeline? [y/n] " yn
  case $yn in
    [Yy]*)
      if [[ "${INTERACTIVE}" == TRUE ]]
      then
        # Run pipeline interactively
        "${SCRIPTDIR}"/TrimMapCount.sh "${SCRIPTDIR}" "${RAWDATADIR}" "${DATADIR}" "${GENOMEDIR}" "${ADAPTER_FILE}"
      else
        # Submit batch job
        sbatch "${SCRIPTDIR}"/TrimMapCount.sh "${SCRIPTDIR}" "${RAWDATADIR}" "${DATADIR}" "${GENOMEDIR}" "${ADAPTER_FILE}"
      fi
      break
      ;;
    [Nn]*)
      exit 0
      ;;
    *)
      echo "  Please answer yes or no."
      ;;
  esac
done

